PeopleForBikes/brokenspoke

- docs/config.toml
Removes the trailing slash in the base URL.
> Fix docs config

- pipelines/brochures/Cargo.toml
- pipelines/brochures/src/main.rs
Fixes the output path of the brochure pipeline.
Drive-by:
- Adds logging to the brochure pipeline.
> Fix output path

- .github/workflows/incubator.yml
Implements the missing workflow for the incubator.
The incubator projects don't need a CI per say, but they do need a
GitHub workflow with a placeholder for the lint, test and build jobs.
Fixes #33
> Implement incubator workflow

- bnacore/src/bundle.rs
- bnacore/src/combine.rs
- bnacore/src/scorecard.rs
This patch fixes the types used in the Infrstructure struct, which were
set too small.
> Fix infrastructure value types

- bnacore/src/scorecard.rs
Ensures that optional arguments are placed last, as they cannot appear
in the middle of the signature in Python.
> Fix Python function argument order

- .github/workflows/bnacore.yml
- .github/workflows/incubator.yml
- .github/workflows/pipelines-brochures.yml
- .github/workflows/pipelines-retrieve.yml
- .github/workflows/spokes.yml
Replaces the Rust GitHub actions coming from `action-rs` as they are
unmaintained. This was also an opportunity to simplify the run calls as
well.
> Update Rust GitHub actions

- .github/workflows/spokes.yml
- incubator/bnapi/migration/src/m20220101_000001_create_table.rs
Seaorm got upgraded requiring the use of another function to create
timestamp fields.
> Fix incubator projects

- bnacore/src/lib.rs
- incubator/bnapi/api/src/main.rs
- pipelines/brochures/Cargo.toml
- pipelines/brochures/src/main.rs
Updates the CI to run the linters on both Ubuntu and Windows.
Drive-bys:
- Fixes CI violations.
> Update CI to handle Windows platform

- lambdas/src/bna-setup.rs
Updates the BNA command in the bna-setup lambda to allow to specify the
name of the S3 bucket where to export the results.
> Update the bna command

- .github/workflows/lambda-deployment-staging.yml
Adds the missing path for the deployment staging workflow.
> Add missing workflow path

- bnacore/src/template.rs
- pipelines/brochures/src/main.rs
Fixes the file name sanitizing logic to prevent special characters (like
apostrophes for instance) to land in the file name.
Drive-by:
- Updates the template version to be used.
- Switches to using `svg2pdf` instead of inkscape.
> Fix brochure pipeline

- bnacore/Cargo.toml
- bnacore/src/lib.rs
- bnacore/src/versioning/mod.rs
Adds a new module for handling versioning. The first implementation is
Calver, and more specifically the Ubuntu format of Calver since it is
the one used by the new BNA to order analysis.
> Add versioning module

- Cargo.toml
- bnacore/Cargo.toml
- lambdas/Cargo.toml
- lambdas/src/bna-sqs-parse.rs
- lambdas/src/lib.rs
Adds Step Machine context to the metadata of the execution pipeline in
or to be able to save the execution status and pin point errors more
easily.
> Add Step Machine Context

- bnacore/Cargo.toml
- bnacore/examples/s3_calver.rs
- bnacore/src/aws/mod.rs
- bnacore/src/aws/s3.rs
Adds a module to perform Calver operations following the PFB naming
convention.
> Add calver module

- .github/workflows/lambda-deployment-staging.yml
- lambdas/Cargo.toml
- lambdas/src/bna-prepare-destination.rs
- lambdas/src/bna-save-results.rs
Adds a new function to save the results of an analysis into the database
via the API.
> Add function to save analysis results to API

- bnacore/src/bundle.rs
- bnacore/src/neon/model.rs
- lambdas/src/bna-save-results.rs
Finalizes the save-results step, ensuring a city is created or updated
when new results are being saved into the database.
Drive-bys:
- Updates compression options in bundle.rs.
> Finalize save-results step

- lambdas/src/bna-fargate-run.rs
Fixes the name of the exporter being used to store the results on S3.
> Fix exporter name

- lambdas/src/bna-fargate-run.rs
- lambdas/src/bna-setup.rs
- lambdas/src/bna-sqs-parse.rs
- lambdas/src/bna-teardown.rs
Since the name of the pipelines are now human readable names, we need to
generate UUIDs to be able to store information about the progress in the
database.
This a a temporary step, and a proper patch with a schema update will
come later.
> Generate pipeline UUIDs

- lambdas/src/bna-fargate-run.rs
- lambdas/src/bna-save-results.rs
- lambdas/src/bna-setup.rs
- lambdas/src/bna-sqs-parse.rs
- lambdas/src/bna-teardown.rs
- lambdas/src/lib.rs
Uses the ID from the pipeline context as the state machine id/bna id.
> Retrieve ID from pipeline context

- lambdas/src/bna-save-results.rs
Ensures the GET /cities endpoint uses values with title case as the
search is case sensitive.
> Fix save results lambda

- lambdas/src/bna-save-results.rs
Fixes the call describing the ECS task running the fargate containers.
> Fix ECS describe task
