.github/workflows/bnacore.yml
bnacore/src/lib.rs
svggloo/Cargo.toml

Adds a workflow for the BNA Core project.
Drive-by:
- Fixes the CI violations.

Add BNACore workflow

---

.github/workflows/bnacore.yml
.github/workflows/docs.yml
.github/workflows/pipelines-brochures.yml
.github/workflows/svggloo.yml

Fix Docs CI

---

.github/workflows/docs.yml

Fixes the tasks deploying the documentation.

Fix Docs Deployment

---

docs/config.toml

Fixes incorrect base URL for the documentation site.

Fixes docs configuration

---

docs/config.toml
docs/content/docs/pipelines/brochures.md

- Fix docs config
- Fix broken image links in docs

fix docs images

---

docs/content/docs/pipelines/brochures.md

Fix broken image links in docs

---

pipelines/brochures/src/main.rs

Handles the error that may happen during the execution of the pipeline
and return an error message to the user.

Handle command error in pipeline

---

docs/content/_index.md
docs/content/docs/overview/overview.md
docs/content/docs/pipelines/brochures.md

Updates the main page, the project overview and the brochure pipeline
instructions.

Update the documentation

---

.github/workflows/pipelines-retrieve.yml

Implements the CI workflow for the retrieve pipeline.
Fixes #40.

Implement retrieve pipeline CI workflow

---

Justfile
bnacore/Cargo.toml
bnacore/src/bundle.rs
brokenspoke-words.txt
docs/content/docs/pipelines/retrieve.md
incubator/bnapi/migration/README.md
incubator/brochure-portal/README.md
spokes/README.md
spokes/src/bundler.rs

Improves the bundler performace by avoiding recompressing zip files.
Fixes PeopleForBikes/brokenspoke#35

Improve the bundler performance

---

pipelines/brochures/src/main.rs

Adjusts the pipeline to circumvent platform limitations.
Fixes #34.

Adjust the pipeline per platform

---

assets/visuals/template-scorecard-pg1-v23.1.svg
pipelines/brochures/src/main.rs

Adjusted the alignment of the value of "Miles of high-stress roads".

Adjust alignment of high stress miles

---

assets/visuals/template-scorecard-pg1-v23.2.svg

Add a white background to the header of the v23.1 scorecard template. Create a new template scorecard for 2023 named
template-scorecard-pg1-v23.2

Fix scorecard templates

---

.github/workflows/lambda-deployment-staging.yml
.github/workflows/lambdas.yml
Cargo.toml
lambdas/Cargo.toml
lambdas/src/bna-setup.rs
lambdas/src/bna-teardown.rs
lambdas/src/lib.rs

Adds lambdas functions to this project, and merge shared components into
the bna core library..
CI/CD workflows have also been implemented.

Add lambdas functions to this project

---

.github/workflows/lambda-deployment-staging.yml

Adds the BNA teardown function to the deployment workflow for staging.

Add teardown function to deployment workflow

---

.github/workflows/lambda-deployment-staging.yml
lambdas/Cargo.toml
lambdas/src/bna-setup.rs
lambdas/src/bna-sqs-parse.rs
lambdas/src/bna-teardown.rs
lambdas/src/lib.rs
lambdas/src/neon/mod.rs
lambdas/src/neon/model.rs

Adds new lambda function for the BNA pipeline.
Due to a cross-compilation issue in the `bnacore` we had to unlink it
and copy/paste the neon module into the lambda project as a quick fix.

Add new lambda function for BNA pipeline

---

lambdas/Cargo.toml
lambdas/src/bna-fargate-run.rs
lambdas/src/bna-fargate-status.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-teardown.rs

Adds new functions to manage the Fargate task lifecycle.

Add new fargate lambda functions

---

.github/workflows/lambda-deployment-staging.yml
bnacore/src/combine.rs
lambdas/Cargo.toml
lambdas/src/scorecard.rs

Adds a new lambda function to generate scorecards.

Add Scorecard Lambda

---

.github/workflows/lambda-deployment-staging.yml

Fixes the lambda deployment workflow.

Fix the lambda deployment workflow

---

incubator/bnapi/api/Cargo.toml
incubator/bnapi/api/src/main.rs
lambdas/Cargo.toml
lambdas/src/bna-fargate-run.rs
lambdas/src/bna-fargate-status.rs
lambdas/src/scorecard.rs

Updates the dependencies and replaces the AWS Config deprecated
functions.

Update the dependencies

---

bnacore/src/aws/mod.rs

Adds function to manipulate secrets from AWS Secrets Manager.

Add AWS helper functions

---

brokenspoke-words.txt
lambdas/README.md
lambdas/src/bna-fargate-run.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-teardown.rs

fixes the markdown linter violations.

Fix linter violations

---

lambdas/src/bna-sqs-parse.rs

Adds a catch-all logging function to the bna-sqs-parse function.

Add catch-all logging.

---

lambdas/src/bna-sqs-parse.rs

Fix API URL

---

lambdas/src/bna-sqs-parse.rs

Ensures the input matches the new structure.

Fix SQS Parse input

---

lambdas/src/bna-fargate-run.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-sqs-parse.rs
lambdas/src/bna-teardown.rs
lambdas/src/lib.rs

Updates all the pipeline tasks to ensure each of them updates the
information in the pipeline table.

 Update all pipeline tasks

---

lambdas/src/bna-fargate-run.rs
lambdas/src/bna-fargate-status.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-teardown.rs

Add a way to catch and log all the errors from the main function.

Add a catch all logging

---

lambdas/src/bna-fargate-run.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-teardown.rs

Fixes the URL used to update the pipeline details.

Fix update pipeline URL

---

bnacore/src/aws/mod.rs
bnacore/src/bundle.rs
bnacore/src/lib.rs
lambdas/src/bna-fargate-run.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-sqs-parse.rs
lambdas/src/bna-teardown.rs
lambdas/src/lib.rs

Refactors the BNACore library and its usage within the lambda functions.

Refactor BNACore

---

Cargo.toml
bnacore/Cargo.toml
bnacore/examples/neon.rs
bnacore/src/neon/mod.rs
bnacore/src/neon/model.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-teardown.rs

Improves neon.tech models and creates a REST client.

Improve neon.tech module

---

bnacore/src/aws/mod.rs
bnacore/src/neon/model.rs
lambdas/src/bna-fargate-run.rs
lambdas/src/bna-fargate-status.rs
lambdas/src/bna-setup.rs
lambdas/src/bna-sqs-parse.rs
lambdas/src/bna-teardown.rs
lambdas/src/lib.rs

Updates pipeline tasks to ensure the pipeline status gets updated
coorectly as long as the pipeline progresses.

Update pipeline tasks

---

lambdas/src/lib.rs

Uses `bnacore::Error` in Results for better error handling.
Drive-by:
- Retrieve the Cognito Authentication URL as a parameter instead of a
secret.

Use bnacore::Error in Results<>

---

lambdas/src/bna-fargate-run.rs

Updates Fargate launch definition to use public subnet.

Update Fargate launch definition

---

bnacore/src/scorecard/scorecard24.rs

Updates the Scorecard24 format.

Update Scorecard24 Format

---

.github/workflows/lambda-deployment-staging.yml
bnacore/examples/s3_calver.rs
bnacore/src/aws/mod.rs
bnacore/src/aws/s3.rs
lambdas/Cargo.toml
lambdas/src/bna-prepare-destination.rs
lambdas/src/lib.rs

Adds a new lambda function which goal is to create the S3 directory
which will be used as a destination to store the analysis results.

Add function to prepare S3 destination

---

lambdas/src/bna-prepare-destination.rs

Adjust the output of the function preparing the destination directory in S3.

Adjust lambda output

---

Cargo.toml
bnacore/Cargo.toml
incubator/bnapi/api/Cargo.toml
incubator/bnapi/entity/Cargo.toml
incubator/bnapi/migration/Cargo.toml
lambdas/Cargo.toml
pipelines/brochures/Cargo.toml
pipelines/retrieve/Cargo.toml
spokes/Cargo.toml

Uses auto-inherit to inherit all the dependencies from the workspace.

Inherit dependencies from workspace

---

lambdas/src/bna-prepare-destination.rs
lambdas/src/bna-save-results.rs
lambdas/src/bna-setup.rs

Adjust the outputs of the BNA pipeline tasks.

Adjust task outputs

---

lambdas/src/bna-fargate-run.rs
lambdas/src/bna-save-results.rs

Fixes the BNA Lambdas inputs/outputs.
Drive-by:
- Adds logging.

Fix BNA lambdas

---

lambdas/src/bna-save-results.rs

Fixes the parsing of the overall scores in the bna-save-results lambda
function.

Fix bna-save-results lambda

---

.github/workflows/lambda-deployment-staging.yml
lambdas/src/bna-save-results.rs

Updates the lambda deploy workflow to force using Amazon Linux 2023 as the runtime.

Update lambda deploy workflow

---

lambdas/src/bna-save-results.rs

Refactor the save-result function to help debugging.

Refactor bna-save-result function

---

lambdas/src/bna-fargate-run.rs

Specify the AWS S3 target directory when running Fargate.

Update Fargate run parameters

---

lambdas/src/bna-save-results.rs

Fixes the save-results functions by adding missing fields that had been
forgotten in the previous iterations.

Fix save-results function

---

lambdas/src/bna-save-results.rs

Checks the status code of each REST request.

Fix save-results.

---

lambdas/src/bna-save-results.rs

Updates the return value of the POST /cities.

Fix save-results

---

lambdas/src/bna-teardown.rs

Updates the teardown step to remove the information and actions that are
not necessary anymore.

Update teardown step

---

lambdas/src/bna-fargate-run.rs
lambdas/src/bna-sqs-parse.rs

Moves the pipeline update requests to the BNA pipeline. The pre-bna
pipeline currently cannot and must not update the pipeline status.

 Move the pipeline update requests 

---

lambdas/src/bna-save-results.rs

Fixes the POST request body to create a new city.

Fix request to create new city

---

lambdas/src/bna-save-results.rs

Add debuggin information

---

lambdas/src/bna-save-results.rs

Fixes the name of the fields in the city model.

Fix city model

---

lambdas/src/bna-save-results.rs

Fix ratings URL

---

lambdas/src/bna-teardown.rs

Updates the pipeline step name to match the new steps from the table.

Fix teardown task

---

.github/workflows/assets.yml
.github/workflows/bnacore.yml
.github/workflows/docs.yml
.github/workflows/incubator.yml
.github/workflows/pipelines-brochures.yml
.github/workflows/pipelines-retrieve.yml
.github/workflows/spokes.yml
docs/config.toml
docs/themes/adidoks/config.toml
docs/themes/adidoks/config.toml.example
docs/themes/zola_easydocs_theme/content/content/section.md
docs/themes/zola_easydocs_theme/content/getting-started/configuration.md
docs/themes/zola_easydocs_theme/content/templates/feeds/index.md

Fixes the Zola action.
Drive-by:
- Pins actions.

Fix Zola action

---

bnacore/src/combine.rs
bnacore/src/lib.rs
bnacore/src/versioning/mod.rs
lambdas/src/scorecard.rs

Fix Clippy violations
